# @path: ~/projects/configs/nix-config/tests/nmt/home/core/base/tmux.nix
# @author: redskaber
# @datetime: 2026-05-11
# @description: nmt::home::core::base::tmux
# @source: home/core/exp/sys/base/tmux.nix
#
# nmt-Plane: dotfile content assertions (zero VM, pure eval)
#
# Asserts:
#   - .config/tmux/tmux.conf (or .tmux.conf) generated by HM
#   - history limit written

{ lib, ... }:

lib.nmt.buildHomeManagerTest {
  description = "tmux: config file content assertions";

  modules = [{
    home = {
      username      = "testuser";
      homeDirectory = "/home/testuser";
      stateVersion  = "25.11";
    };

    programs.tmux = {
      enable       = true;
      historyLimit = 50000;
      keyMode      = "vi";
      terminal     = "tmux-256color";
    };
  }];

  tests = {
    "tmux: config file exists" = {
      path   = ".config/tmux/tmux.conf";
      exists = true;
    };

    "tmux: history-limit written" = {
      path     = ".config/tmux/tmux.conf";
      contains = [ "history-limit" "50000" ];
    };

    "tmux: vi mode written" = {
      path     = ".config/tmux/tmux.conf";
      contains = [ "vi" ];
    };
  };
}
