# @path: ~/projects/configs/nix-config/hosts/nixos/default.nix
# @author: redskaber
# @datetime: 2026-03-15
# @description: hosts::nixos — host-specific configuration override
#
# This file provides host-specific overrides for the "nixos" host.
# It imports the hardware config and can override shared.nix values.
#
# Multi-host design:
#   hosts/<hostname>/default.nix — host entry (imports hardware.nix + overrides)
#   hosts/<hostname>/hardware.nix — auto-generated by nixos-generate-config
#   hosts/<hostname>/shared.nix — optional host-specific shared overrides
#
# To add a new host:
#   1. mkdir hosts/<new-hostname>
#   2. cp hosts/nixos/default.nix hosts/<new-hostname>/default.nix
#   3. nixos-generate-config > hosts/<new-hostname>/hardware.nix
#   4. Add host to flake.nix nixosConfigurations

{ ... }:

{
  # Import auto-detected hardware configuration
  imports = [
    ./hardware.nix
  ];

  # Host-specific overrides go here (optional)
  # Example: networking.hostName = "nixos";
}
