# @path: ~/projects/configs/nix-config/hosts/nixos/default.nix
# @author: redskaber
# @datetime: 2026-03-15
# @description: hosts::nixos — host-specific configuration override
#
# This file provides host-specific overrides for the "nixos" host.
# It imports the hardware config and can override shared.nix values.
#
# Multi-host design (T2.3/T2.4):
#   hosts/<hostname>/default.nix — host entry (imports hardware.nix + overrides)
#   hosts/<hostname>/hardware.nix — auto-generated by nixos-generate-config
#   hosts/<hostname>/shared.nix — optional host-specific shared overrides
#
# To add a new host (no flake.nix edit needed — hosts/ is enumerated):
#   1. mkdir hosts/<new-hostname>
#   2. cp hosts/nixos/default.nix hosts/<new-hostname>/default.nix (adjust hardware)
#   3. nixos-generate-config > hosts/<new-hostname>/hardware.nix
#   4. (optional) write hosts/<new-hostname>/shared.nix policy overrides
#   → available as nixosConfigurations.<new-hostname> / <user>@<new-hostname>

{ ... }:

{
  # Import auto-detected hardware configuration
  imports = [
    ./hardware.nix
  ];

  # Host-specific overrides go here (optional)
  # Example: networking.hostName = "nixos";

  # Machine fingerprints (sunk from nixos/core/drive/nvidia-prime.nix):
  # the generic drive layer must stay hardware-agnostic.
  hardware.nvidia.prime = {
    intelBusId = "PCI:0:2:0"; # 00:02.0
    nvidiaBusId = "PCI:6:0:0"; # 06:00.0
  };
}
