# @path: ~/projects/configs/nix-config/nixos/core/base/hardware.nix
# @author: redskaber
# @datetime: 2026-01-13
# @description: nixos::core::base::hardware — auto-detected hardware config
#
# NOTE: This file is generated by `nixos-generate-config` (or `just hardware-generate`).
#       It contains machine-specific UUIDs and hardware detection.
#       Do not edit manually; re-generate on new hardware.
#       For multi-host support, this file should be moved to hosts/<hostname>/hardware.nix.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c2624c51-329a-4f2b-acc2-c829d6f3e324";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/974A-6A53";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/50edded4-41e4-4f7e-8e97-fd803b1eb420"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
