# @path: ~/projects/configs/nix-config/nixos/hardware-configuration.nix
# @author: redskaber
# @datetime: 2026-01-13
# @description: nixos hardware configuration.
# - Do not modify this file!  It was generated by ‘nixos-generate-config’
# - and may be overwritten by future invocations.
# - Please make changes to /etc/nixos/configuration.nix instead.


{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4ca724ea-aa6f-4be9-8a86-79a602cc835a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3344-86BF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f39e75e0-114c-49bf-8f7b-f89ead81519f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

