# @path: ~/projects/configs/nix-config/tests/nmt/home/core/exp/sys/shell/zsh.nix
# @author: redskaber
# @datetime: 2026-05-11
# @description: nmt::home::core::exp::sys::shell::zsh
# @source: home/core/exp/sys/shell/zsh.nix
#
# nmt-Plane: dotfile content assertions (zero VM, pure eval)
#
# Asserts:
#   - .zshrc generated by HM
#   - zsh-autosuggestions plugin sourced
#   - zsh-syntax-highlighting plugin sourced
#   - HISTSIZE defined
#   - vi = nvim alias written

{ lib, ... }:

lib.nmt.buildHomeManagerTest {
  description = "zsh: .zshrc content assertions";

  modules = [{
    home = {
      username      = "testuser";
      homeDirectory = "/home/testuser";
      stateVersion  = "25.11";
    };

    programs.zsh = {
      enable    = true;
      autosuggestion.enable         = true;
      syntaxHighlighting.enable     = true;
      historySubstringSearch.enable = true;
      history = {
        size = 50000;
        save = 50000;
      };
      shellAliases = {
        vi  = "nvim";
        vim = "nvim";
        ll  = "ls -la";
      };
    };
  }];

  tests = {
    "zsh: .zshrc generated" = {
      path   = ".zshrc";
      exists = true;
    };

    "zsh: autosuggestions sourced" = {
      path     = ".zshrc";
      contains = [ "zsh-autosuggestions" ];
    };

    "zsh: syntax-highlighting sourced" = {
      path     = ".zshrc";
      contains = [ "zsh-syntax-highlighting" ];
    };

    "zsh: HISTSIZE present" = {
      path     = ".zshrc";
      contains = [ "HISTSIZE" ];
    };

    "zsh: vi alias present" = {
      path     = ".zshrc";
      contains = [ "nvim" ];
    };
  };
}
