# @path: ~/projects/configs/nix-config/.github/workflows/ci.yml
# @author: redskaber
# @date: 2026-03-30

name: Nix Config CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # 每天 UTC 时间 02:00 运行（检查依赖更新）
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nix formatting
        run: |
          # Optional 
          nix fmt --extra-experimental-features pipe-operators -- --check .
          # nix run .#formatter.${{ matrix.system }} -- --check .

      - name: Check Nix syntax
        run: |
          nix-instantiate --eval-only --expr 'import ./flake.nix'

  # evaluate:
  # security:

